---
- hosts: ec2_instances
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name:
          - docker.io
          - python3-pip
        state: present

    - name: Clone Node.js app repository
      git:
        repo: https://github.com/Roleyner/api-with-express-and-handlebars.git
        dest: /var/www/html/nodejs-app

    - name: Build Docker image
      command: docker build -t nodejs-app /var/www/html/nodejs-app

    - name: Run Docker container
      command: docker run -d -p 3000:3000 --name nodejs-app-container nodejs-app
